apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: load-generaror-deploy-task
  namespace: demo
  labels:
    app: load-generator
spec:
  params:
    - name: endpoint
      type: string
    - default: '10'
      name: connections
      type: string
    - default: '30'
      name: duration
      type: string
    - default: '2'
      name: timeout
      type: string
    - default: json
      name: outFormat
      type: string
    - default: 'false'
      name: stopOnError
      type: string
    - default: '50,150,155'
      name: payloadSizes
      type: string
    - default: 'true'
      name: randPayload
      type: string
    - default: 'true'
      name: randReqMode
      type: string
    - default: '50'
      name: threadSleepMS
      type: string
    - default: '10'
      name: ltReqPayloadSizeFactor
      type: string
    - default: 'false'
      name: ltReqFirstSizeOnly
      type: string
    - default: 'false'
      name: traceActive
      type: string
    - default: 'false'
      name: createSpikes
      type: string
    - default: '2'
      name: spikeConnections
      type: string
    - default: '1'
      name: spikeDurationLowerBound
      type: string
    - default: '5'
      name: spikeDurationUpperBound
      type: string
    - default: 'false'
      name: randomSpikeDuration
      type: string
    - default: '3'
      name: spikeRepetitionLoBound
      type: string
    - default: '6'
      name: spikeRepetitionHiBound
      type: string
    - default: 'false'
      name: randomSpikeRepeat
      type: string
    - default: '9090'
      name: prometheusPort
      type: string
    - default: 'false'
      name: detailedOutput
      type: string
  steps:
    - env:
        - name: CREATESPIKES
          value: $(inputs.params.createSpikes)
        - name: SPIKECONNECTIONS
          value: $(inputs.params.spikeConnections)
        - name: PROMETHEUSPORT
          value: $(inputs.params.prometheusPort)
        - name: SPIKEDURATIONLOWERBOUND
          value: $(inputs.params.spikeDurationLowerBound)
        - name: SPIKEDURATIONUPPERBOUND
          value: $(inputs.params.spikeDurationUpperBound)
        - name: RANDOMSPIKEDURATION
          value: $(inputs.params.randomSpikeDuration)
        - name: SPIKEREPETITIONINTLOBOUND
          value: $(inputs.params.spikeRepetitionLoBound)
        - name: SPIKEREPETITIONINTHIBOUND
          value: $(inputs.params.spikeRepetitionHiBound)
        - name: RANDOMSPIKEREPEAT
          value: $(inputs.params.randomSpikeRepeat)
        - name: DETAILEDOUTPUT
          value: $(inputs.params.detailedOutput)
        - name: TRACEACTIVE
          value: $(inputs.params.traceActive)
        - name: CONNECTIONS
          value: $(inputs.params.connections)
        - name: DURATION
          value: $(inputs.params.duration)
        - name: TIMEOUTSECONDS
          value: $(inputs.params.timeout)
        - name: ENDPOINT
          value: $(inputs.params.endpoint)
        - name: OUTPUT
          value: $(inputs.params.outFormat)
        - name: STOPONERROR
          value: $(inputs.params.stopOnError)
        - name: THREADSLEEPMS
          value: $(inputs.params.threadSleepMS)
        - name: RANDREQMODE
          value: $(inputs.params.randReqMode)
        - name: RANDPAYLOAD
          value: $(inputs.params.randPayload)
        - name: PAYLOADSIZES
          value: $(inputs.params.payloadSizes)
        - name: LTREQPAYLOADSIZEFACTOR
          value: $(inputs.params.ltReqPayloadSizeFactor)
        - name: LTREQFIRSTSIZEONLY
          value: $(inputs.params.ltReqFirstSizeOnly)
      image: 'quay.io/avitui/load-generator:v1'
      name: load-generator-task
      ports:
        - name: 9090-tcp
          containerPort: 9090
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: '1'
          memory: 2Gi
