kind: Service
apiVersion: v1
metadata:
  name: influxdb
  namespace: demo
  labels:
    app: influxdb
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: influxdb
