apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: load-generator
  name: load-generator-monitor
  namespace: demo
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: metrics-app
    - interval: 5s
      path: /metrics
      port: metrics-node
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: load-generator
